version: 2
updates:
  # Keep GitHub Actions up-to-date (weekly)
  - package-ecosystem: github-actions
    directory: "/"
    rebase-strategy: auto
    schedule:
      interval: weekly
      time: "06:00"
      timezone: "Australia/Sydney"
    open-pull-requests-limit: 99
    assignees:
      ["bunty989"]

  # NPM dependencies for the TypeScript project (daily)
  - package-ecosystem: "npm"
    directory: "/" # Location of package.json
    rebase-strategy: auto
    schedule:
      interval: daily
      time: "06:00"
      timezone: "Australia/Sydney"
    open-pull-requests-limit: 99
    assignees:
      ["bunty989"]