name: Auto Assignee Assignment

on:
  issues:
    types: [ opened ]
  pull_request:
    types: [ opened, ready_for_review, converted_to_draft ]
  pull_request_target:
    types: [ opened, ready_for_review, converted_to_draft ]

env:
  ISSUE_NUMBER: ${{ github.event.issue.number }}

permissions:
  issues: write
  pull-requests: write

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - name: 'Auto-assign issue'
        uses: pozil/auto-assign-issue@v2.2.0
        with:
          assignees: ${{github.actor}}
          repo-token: ${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}
          numOfAssignee: 1
          allowSelfAssign: true